services:
  - type: web
    name: weather-dashboard
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENWEATHERMAP_API_KEY
        sync: false